### ISSUE TITLE
Facilitate pushing current branch to origin

### ISSUE THREAD

**Issue by hammer** [ryan-williams/git-helpers#56]
When working on a branch I find myself doing `$ git push origin <current-branch>` regularly. It's possible to retrieve `<current-branch>` with `$ git symbolic-ref --short HEAD`. I was thinking it could be handy to have a `git-push-cb` helper that does ``$ git push origin `git symbolic-ref --short HEAD` ``. Does that seem reasonable?

**Comment by ryan-williams** [comment]
pretty reasonable! A couple of notes:

* This repo contains a [`git current-branch`](https://github.com/ryan-williams/git-helpers/blob/d2a8fd83453da347c4b9a8c081d32386d0e400be/branch/git-current-branch) helper that is basically identical to your `symbolic-ref` magic
    * aliases: [`git cb`](https://github.com/ryan-williams/git-helpers/blob/d2a8fd83453da347c4b9a8c081d32386d0e400be/branch/.gitconfig#L7), [`g cb`](https://github.com/ryan-williams/git-helpers/blob/d2a8fd83453da347c4b9a8c081d32386d0e400be/aliases/g), [`gcb`](https://github.com/ryan-williams/git-helpers/blob/d2a8fd83453da347c4b9a8c081d32386d0e400be/branch/.git-rc#L11), you know the drill :)
* this repo also contains [`git push-to-origin-master`](https://github.com/ryan-williams/git-helpers/blob/3126cc6c259153750df44098fdfe58cfbdadc308/push/git-push-to-origin-master) (aka [`g pm`](https://github.com/ryan-williams/git-helpers/blob/3126cc6c259153750df44098fdfe58cfbdadc308/push/.gitconfig#L4) / [`gpm`](https://github.com/ryan-williams/git-helpers/blob/3126cc6c259153750df44098fdfe58cfbdadc308/push/.git-rc#L2)), which pushes the current branch to `origin/master`. I use it pretty frequently, but it is slightly different from what you've requested here, so just to be clear, you want something that basically wraps `git push origin "$(g cb)"`?

**Comment by ryan-williams** [comment]
how about: `g po [optional branch name]` (`git push-origin`, defaulting the branch name to current branch)? so your common case would just be `gpo` or `g po`

**Comment by hammer** [comment]
yeah seems reasonable.
