### ISSUE TITLE
`git squash master` tries to squash all commits

### ISSUE THREAD

**Issue by danvk** [ryan-williams/git-helpers#57]
I would have expected it to squash all the commits from master to current HEAD.

**Comment by ryan-williams** [comment]
yea it is [currently assuming](https://github.com/ryan-williams/git-helpers/blob/master/commit/git-squash#L9-L16) any lone cmdline argument is a SHA range like `abc..def`. will have a look at making it more robust

**Comment by danvk** [comment]
If there's no `..` in the arg, maybe add `..HEAD`?
