### ISSUE TITLE
`github path/to/file` should open that file in the browser

### ISSUE THREAD

**Issue by danvk** [ryan-williams/git-helpers#59]
Would be helpful for sending out links to files.

**Comment by ryan-williams** [comment]
bonus points if it opens that file in the tree that the local repo is currently in :)

**Comment by danvk** [comment]
there's no guarantee that your current commit exists on github, though.

**Comment by ryan-williams** [comment]
good point.
1. should that be handled as a special case?
2. or should this functionality always assume that the `path/to/file` given is a path that is resolvable on `origin/master`. 

If the latter:
* should we open it with the commit at the top of `origin/master` in the url, or simply the `master` tree?
* what if `path/to/file` doesn't exist 
    * in the local `HEAD` tree?
    * on `origin/master`?

just brainstorming. 1) still sounds maybe most sensible to me and most in line with the main use case (send someone a link to this file as I currently see it)

**Comment by ryan-williams** [comment]
for posterity, `git branch -r --contains "$(git sha HEAD)" | grep -q 'origin/'` is a good approximation for "does my local `HEAD` exist on GitHub"?
