### ISSUE TITLE
Error from bashrc

### ISSUE THREAD

**Issue by danvk** [ryan-williams/git-helpers#61]
I just saw this when I opened a shell:

```
error: could not lock config file /Users/danvk/.git-helpers.config: File exists
error: could not lock config file /Users/danvk/.gitconfig: File exists
```

I opened five more shells and didn't see it. Any guesses?

**Comment by ryan-williams** [comment]
weird, so this happened to you transiently just one time?

**Comment by danvk** [comment]
Seems to be a one-time thing. I'll update if it happens again.

**Comment by ryan-williams** [comment]
thanks! I'll update if I have any ideas
